apiVersion: v2
name: pgop
description: A Kubernetes operator for managing PostgreSQL databases
type: application
version: 0.4.1
appVersion: "v0.4.1"
keywords:
  - postgresql
  - operator
  - kubernetes
home: https://github.com/ruckc/pgop
sources:
  - https://github.com/ruckc/pgop
maintainers:
  - name: ruckc
    url: https://github.com/ruckc
