resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: example.com/pgop
  newTag: coverage-v1
- name: ghcr.io/ruckc/pgop
  newName: ghcr.io/ruckc/pgop
  newTag: latest
