/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"maps"
	"slices"
	"strings"
	"time"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	logf "sigs.k8s.io/controller-runtime/pkg/log"

	postgresv1alpha1 "github.com/ruckc/pgop/api/v1alpha1"
	"github.com/ruckc/pgop/internal/postgres"
)

const (
	configVolumeName = "config"
	configMountPath  = "/etc/pgop/config"
	configFileName   = "postgresql.conf"
	// configFilePath is the generated main configuration file the server is
	// started with (-c config_file=...) while spec.parameters is set.
	configFilePath       = configMountPath + "/" + configFileName
	configFileMode int32 = 0o644

	// autoConfFileName is the file ALTER SYSTEM writes, in the data directory.
	autoConfFileName = "postgresql.auto.conf"

	// pgContextPostmaster is the pg_settings.context of parameters that can
	// only change with a server restart.
	pgContextPostmaster = "postmaster"

	// Requeue intervals while applying spec.parameters.
	parametersReloadCheckDelay = 2 * time.Second
	parametersPollInterval     = 10 * time.Second
	parametersRetryInterval    = 30 * time.Second
	parametersInvalidRecheck   = time.Minute
	parametersRecheckInterval  = 5 * time.Minute
)

// ParameterServer is the PostgreSQL access needed to apply spec.parameters.
// *postgres.Client implements it.
type ParameterServer interface {
	ConfigFile(ctx context.Context) (string, error)
	FileSettings(ctx context.Context) ([]postgres.FileSetting, error)
	Settings(ctx context.Context) ([]postgres.Setting, error)
	ReloadConfig(ctx context.Context) error
	Close() error
}

// connectParameterServer connects to PostgreSQL with cfg.
func connectParameterServer(_ context.Context, cfg postgres.ConnectionConfig) (ParameterServer, error) {
	return postgres.NewClient(cfg)
}

// configMapName is the name of the ConfigMap holding the generated
// configuration file.
func configMapName(cluster *postgresv1alpha1.Cluster) string {
	return cluster.Name + "-config"
}

// confValueEscaper escapes a value for a single-quoted postgresql.conf string.
// The server unescapes doubled single quotes and backslash sequences (\n, \r
// included) in quoted values, so the value round-trips exactly
// (pg_file_settings.setting shows it unchanged) and can never end the line.
var confValueEscaper = strings.NewReplacer(`\`, `\\`, `'`, `''`, "\n", `\n`, "\r", `\r`)

// quoteConfValue quotes a value for postgresql.conf.
func quoteConfValue(v string) string {
	return "'" + confValueEscaper.Replace(v) + "'"
}

// parametersWithLineBreaks returns the parameters whose values contain line
// breaks. They are rendered safely, but no PostgreSQL parameter needs one, so
// they are reported as invalid rather than applied.
func parametersWithLineBreaks(params map[string]string) []string {
	var names []string
	for k, v := range params {
		if strings.ContainsAny(v, "\r\n") {
			names = append(names, k)
		}
	}
	slices.Sort(names)
	return names
}

// renderPostgresConf renders spec.parameters as the main configuration file.
// It first includes the data directory's postgresql.conf, so the defaults the
// image and initdb wrote there still apply and spec.parameters overrides them
// (the last setting in the file wins). Keys are sorted, so the output (and its
// hash) is deterministic. Returns the file and its hash.
func renderPostgresConf(params map[string]string, pgdata string) (string, string) {
	var b strings.Builder
	b.WriteString("# Generated by pgop from Cluster spec.parameters. Changes are overwritten.\n")
	b.WriteString("include_if_exists " + quoteConfValue(pgdata+"/postgresql.conf") + "\n")
	for _, k := range slices.Sorted(maps.Keys(params)) {
		b.WriteString(k + " = " + quoteConfValue(params[k]) + "\n")
	}
	conf := b.String()
	sum := sha256.Sum256([]byte(conf))
	return conf, hex.EncodeToString(sum[:])
}

// duplicateParameters returns the parameter names that occur more than once
// when compared case-insensitively, as PostgreSQL does.
func duplicateParameters(params map[string]string) []string {
	seen := map[string]int{}
	for k := range params {
		seen[strings.ToLower(k)]++
	}
	var dups []string
	for k, n := range seen {
		if n > 1 {
			dups = append(dups, k)
		}
	}
	slices.Sort(dups)
	return dups
}

// postgresServerArgs returns the container args: the generated config file
// (while spec.parameters is set) followed by the TLS options. nil when neither
// is used, so the image default CMD runs exactly as before; TLS-only clusters
// get the same args as before spec.parameters existed.
func postgresServerArgs(cluster *postgresv1alpha1.Cluster) []string {
	tlsArgs := postgresTLSArgs(cluster.Spec.TLS)
	if len(cluster.Spec.Parameters) == 0 {
		return tlsArgs
	}
	args := []string{postgresBinary, "-c", "config_file=" + configFilePath}
	if len(tlsArgs) > 0 {
		args = append(args, tlsArgs[1:]...) // drop the leading "postgres"
	}
	return args
}

// postgresConfigVolumes returns the volume and mount for the generated
// configuration file (both nil while spec.parameters is empty).
func postgresConfigVolumes(cluster *postgresv1alpha1.Cluster) ([]corev1.Volume, []corev1.VolumeMount) {
	if len(cluster.Spec.Parameters) == 0 {
		return nil, nil
	}
	return []corev1.Volume{{
			Name: configVolumeName,
			VolumeSource: corev1.VolumeSource{
				ConfigMap: &corev1.ConfigMapVolumeSource{
					LocalObjectReference: corev1.LocalObjectReference{Name: configMapName(cluster)},
					DefaultMode:          new(configFileMode),
				},
			},
		}},
		[]corev1.VolumeMount{{Name: configVolumeName, MountPath: configMountPath, ReadOnly: true}}
}

// reconcileConfigMap creates or updates the ConfigMap with the generated
// configuration file while spec.parameters is set. Changing a parameter only
// changes this ConfigMap, never the pod template, so it does not roll the pod.
func (r *ClusterReconciler) reconcileConfigMap(ctx context.Context, cluster *postgresv1alpha1.Cluster, layout postgresLayout) error {
	if len(cluster.Spec.Parameters) == 0 {
		return nil
	}
	conf, _ := renderPostgresConf(cluster.Spec.Parameters, layout.PGDATA)
	cm := &corev1.ConfigMap{}
	err := r.Get(ctx, types.NamespacedName{Name: configMapName(cluster), Namespace: cluster.Namespace}, cm)
	if err == nil {
		if !metav1.IsControlledBy(cm, cluster) {
			return fmt.Errorf("ConfigMap %q exists and is not owned by the Cluster", cm.Name)
		}
		if cm.Data[configFileName] == conf && len(cm.Data) == 1 {
			return nil
		}
		cm.Data = map[string]string{configFileName: conf}
		return r.Update(ctx, cm)
	}
	if !apierrors.IsNotFound(err) {
		return err
	}
	cm = &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      configMapName(cluster),
			Namespace: cluster.Namespace,
			Labels: map[string]string{
				LabelAppName:      AppNamePostgresql,
				LabelAppInstance:  cluster.Name,
				LabelAppManagedBy: LabelValuePgop,
			},
		},
		Data: map[string]string{configFileName: conf},
	}
	if err := controllerutil.SetControllerReference(cluster, cm, r.Scheme); err != nil {
		return err
	}
	return r.Create(ctx, cm)
}

// cleanupConfigMap deletes the generated configuration ConfigMap once
// spec.parameters is empty. It runs after the StatefulSet stopped referencing
// it.
func (r *ClusterReconciler) cleanupConfigMap(ctx context.Context, cluster *postgresv1alpha1.Cluster) error {
	if len(cluster.Spec.Parameters) > 0 {
		return nil
	}
	cm := &corev1.ConfigMap{}
	err := r.Get(ctx, types.NamespacedName{Name: configMapName(cluster), Namespace: cluster.Namespace}, cm)
	if apierrors.IsNotFound(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !metav1.IsControlledBy(cm, cluster) {
		return nil
	}
	return client.IgnoreNotFound(r.Delete(ctx, cm))
}

// parameterAssessment is what the server reports about the generated
// configuration file.
type parameterAssessment struct {
	// UsesGeneratedFile: the server was started with the generated file.
	UsesGeneratedFile bool
	// Synced: the file the server would read now has exactly the desired
	// parameters (the kubelet updated the mounted ConfigMap).
	Synced bool
	// Invalid are entries the server rejects (unknown names, invalid values
	// of parameters that do not need a restart). No reload is attempted.
	Invalid []string
	// InvalidAfterReload are rejected entries of restart-only parameters
	// that the server did not mark pending_restart after a reload, i.e.
	// invalid values. Only meaningful once the current file was reloaded.
	InvalidAfterReload []string
	// Pending are all parameters with pending_restart.
	Pending []string
	// RestartNeeded: a pending parameter comes from spec.parameters (or was
	// removed from it).
	RestartNeeded bool
	// Overridden are desired parameters whose value comes from
	// postgresql.auto.conf (ALTER SYSTEM).
	Overridden []string
}

// assessParameters compares the desired parameters with what the server
// reports (SHOW config_file, pg_file_settings, pg_settings). Names are
// compared case-insensitively, as PostgreSQL does.
func assessParameters(params map[string]string, configFile string, files []postgres.FileSetting,
	settings []postgres.Setting, autoConfPath string) parameterAssessment {
	a := parameterAssessment{UsesGeneratedFile: configFile == configFilePath}

	desired := make(map[string]string, len(params))
	for k, v := range params {
		desired[strings.ToLower(k)] = v
	}
	byName := make(map[string]postgres.Setting, len(settings))
	for _, s := range settings {
		byName[strings.ToLower(s.Name)] = s
	}

	inFile := map[string]string{}
	for _, f := range files {
		if f.SourceFile != configFilePath {
			continue
		}
		name := strings.ToLower(f.Name)
		if name != "" {
			inFile[name] = f.Setting
		}
		if f.Error == "" {
			continue
		}
		entry := fmt.Sprintf("%s: %s", f.Name, f.Error)
		if f.Name != "" {
			entry = fmt.Sprintf("%s = %s: %s", f.Name, quoteConfValue(f.Setting), f.Error)
		}
		// A restart-only parameter whose value differs from the running one
		// is reported as an error too ("setting could not be applied"); only
		// after a reload does pending_restart tell it apart from an invalid
		// value.
		if s, known := byName[name]; known && s.Context == pgContextPostmaster {
			if !s.PendingRestart {
				a.InvalidAfterReload = append(a.InvalidAfterReload, entry)
			}
			continue
		}
		a.Invalid = append(a.Invalid, entry)
	}
	a.Synced = maps.Equal(desired, inFile)

	for _, s := range settings {
		name := strings.ToLower(s.Name)
		_, wanted := desired[name]
		if s.PendingRestart {
			a.Pending = append(a.Pending, s.Name)
			if wanted || s.SourceFile == configFilePath {
				a.RestartNeeded = true
			}
		}
		if wanted && s.SourceFile == autoConfPath {
			a.Overridden = append(a.Overridden, s.Name)
		}
	}
	slices.Sort(a.Pending)
	slices.Sort(a.Overridden)
	return a
}

// setParametersCondition sets the ParametersApplied condition on the
// in-memory Cluster and emits an event when the reason changes to one worth
// surfacing.
func (r *ClusterReconciler) setParametersCondition(cluster *postgresv1alpha1.Cluster, status metav1.ConditionStatus, reason, message string) {
	prev := meta.FindStatusCondition(cluster.Status.Conditions, ConditionTypeParametersApplied)
	changed := prev == nil || prev.Reason != reason || prev.Message != message
	meta.SetStatusCondition(&cluster.Status.Conditions, metav1.Condition{
		Type:               ConditionTypeParametersApplied,
		Status:             status,
		ObservedGeneration: cluster.Generation,
		Reason:             reason,
		Message:            message,
	})
	if r.Recorder == nil || !changed {
		return
	}
	switch reason {
	case ReasonInvalidParameter, ReasonOverriddenByAlterSystem:
		r.Recorder.Eventf(cluster, nil, corev1.EventTypeWarning, reason, "ApplyParameters", "%s", message)
	}
}

// reconcileParameters applies spec.parameters to the running server: it waits
// until the server sees the generated file as desired, reloads it once per
// file version, and restarts the pod once when a parameter needs a restart.
// The outcome is reported in the ParametersApplied condition and
// status.pendingRestart; problems never fail the reconcile or change
// readiness. Returns when to check again (0: no need).
func (r *ClusterReconciler) reconcileParameters(ctx context.Context, cluster *postgresv1alpha1.Cluster, ready bool, pods []corev1.Pod) time.Duration {
	params := cluster.Spec.Parameters
	if len(params) == 0 {
		meta.RemoveStatusCondition(&cluster.Status.Conditions, ConditionTypeParametersApplied)
		cluster.Status.ParametersHash = ""
		cluster.Status.PendingRestart = nil
		return 0
	}

	if dups := duplicateParameters(params); len(dups) > 0 {
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonInvalidParameter,
			fmt.Sprintf("Parameter names are case-insensitive; set each only once: %s", strings.Join(dups, ", ")))
		return 0
	}
	if bad := parametersWithLineBreaks(params); len(bad) > 0 {
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonInvalidParameter,
			fmt.Sprintf("Parameter values must not contain line breaks: %s", strings.Join(bad, ", ")))
		return 0
	}
	layout, err := resolvePostgresLayout(cluster)
	if err != nil {
		// Reported through the Available condition by reconcileStatefulSet.
		return 0
	}
	_, hash := renderPostgresConf(params, layout.PGDATA)

	if !ready {
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonWaitingForServer,
			"Waiting for the PostgreSQL pod to become ready")
		return 0 // updateStatus requeues while the Cluster is not ready
	}
	rolledOut, err := r.statefulSetRolledOut(ctx, cluster)
	if err != nil || !rolledOut {
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonWaitingForServer,
			"Waiting for the StatefulSet rollout to finish")
		return parametersPollInterval
	}

	a, err := r.readParameterState(ctx, cluster, params, layout)
	if err != nil {
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonWaitingForServer,
			fmt.Sprintf("Cannot read the server configuration: %v", err))
		return parametersRetryInterval
	}

	switch {
	case !a.UsesGeneratedFile:
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonWaitingForSync,
			"Waiting for the pod to restart with the generated configuration file")
		return parametersPollInterval
	case !a.Synced:
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonWaitingForSync,
			"Waiting for the updated configuration file to reach the pod")
		return parametersPollInterval
	case len(a.Invalid) > 0:
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonInvalidParameter,
			"The server rejects: "+strings.Join(a.Invalid, "; "))
		return parametersInvalidRecheck
	}

	if cluster.Status.ParametersHash != hash {
		if err := r.reloadForParameters(ctx, cluster, pods); err != nil {
			r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonWaitingForServer,
				fmt.Sprintf("Reloading the server configuration failed: %v", err))
			return parametersRetryInterval
		}
		cluster.Status.ParametersHash = hash
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonParametersReloading,
			"Reloaded the server configuration; checking which parameters need a restart")
		// pg_reload_conf() only signals the server; look again shortly.
		return parametersReloadCheckDelay
	}

	if len(a.InvalidAfterReload) > 0 {
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonInvalidParameter,
			"The server rejects: "+strings.Join(a.InvalidAfterReload, "; "))
		return parametersInvalidRecheck
	}

	cluster.Status.PendingRestart = a.Pending
	if a.RestartNeeded {
		msg := "Restarting the PostgreSQL pod to apply: " + strings.Join(a.Pending, ", ")
		if err := r.restartForParameters(ctx, cluster, hash); err != nil {
			msg = fmt.Sprintf("Parameters need a restart (%s) and restarting the pod failed: %v",
				strings.Join(a.Pending, ", "), err)
		}
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonPendingRestart, msg)
		return parametersPollInterval
	}

	if len(a.Overridden) > 0 {
		r.setParametersCondition(cluster, metav1.ConditionFalse, ReasonOverriddenByAlterSystem,
			fmt.Sprintf("ALTER SYSTEM (%s) overrides: %s; run ALTER SYSTEM RESET for them to use spec.parameters",
				autoConfFileName, strings.Join(a.Overridden, ", ")))
		return parametersRecheckInterval
	}

	msg := "All parameters are in effect"
	if len(a.Pending) > 0 {
		msg += fmt.Sprintf("; the server reports a pending restart for parameters not set by spec.parameters: %s",
			strings.Join(a.Pending, ", "))
	}
	r.setParametersCondition(cluster, metav1.ConditionTrue, ReasonParametersApplied, msg)
	// Look again now and then: ALTER SYSTEM changes are not watchable.
	return parametersRecheckInterval
}

// statefulSetRolledOut reports whether the StatefulSet has no update in
// progress, so the server being queried runs the current pod template.
func (r *ClusterReconciler) statefulSetRolledOut(ctx context.Context, cluster *postgresv1alpha1.Cluster) (bool, error) {
	sts := &appsv1.StatefulSet{}
	if err := r.Get(ctx, types.NamespacedName{Name: cluster.Name, Namespace: cluster.Namespace}, sts); err != nil {
		return false, err
	}
	return sts.Status.UpdateRevision == sts.Status.CurrentRevision, nil
}

// connectForParameters connects to the server as the operator: to the
// primary, or, when dialAddress is set, to the instance at that pod address.
func (r *ClusterReconciler) connectForParameters(ctx context.Context, cluster *postgresv1alpha1.Cluster, dialAddress string) (ParameterServer, error) {
	cluster.Status.SecretName = cluster.Name + "-credentials"
	cfg, err := operatorConnectionConfig(ctx, r.Client, cluster, defaultDatabaseName)
	if err != nil {
		return nil, err
	}
	cfg.DialAddress = dialAddress
	connect := r.ConnectParameterServer
	if connect == nil {
		connect = connectParameterServer
	}
	return connect(ctx, cfg)
}

// readParameterState queries the server and assesses spec.parameters.
func (r *ClusterReconciler) readParameterState(ctx context.Context, cluster *postgresv1alpha1.Cluster,
	params map[string]string, layout postgresLayout) (parameterAssessment, error) {
	srv, err := r.connectForParameters(ctx, cluster, "")
	if err != nil {
		return parameterAssessment{}, err
	}
	defer func() { _ = srv.Close() }()
	configFile, err := srv.ConfigFile(ctx)
	if err != nil {
		return parameterAssessment{}, err
	}
	files, err := srv.FileSettings(ctx)
	if err != nil {
		return parameterAssessment{}, err
	}
	settings, err := srv.Settings(ctx)
	if err != nil {
		return parameterAssessment{}, err
	}
	return assessParameters(params, configFile, files, settings, layout.PGDATA+"/"+autoConfFileName), nil
}

// reloadForParameters runs pg_reload_conf() on the primary and on every
// ready standby (each reached by its pod address): all instances mount the
// same generated file, but a reload only affects the server it runs on.
func (r *ClusterReconciler) reloadForParameters(ctx context.Context, cluster *postgresv1alpha1.Cluster, pods []corev1.Pod) error {
	reload := func(dialAddress string) error {
		srv, err := r.connectForParameters(ctx, cluster, dialAddress)
		if err != nil {
			return err
		}
		defer func() { _ = srv.Close() }()
		return srv.ReloadConfig(ctx)
	}
	if err := reload(""); err != nil {
		return err
	}
	standbys := readyStandbyAddresses(cluster, pods)
	for _, name := range slices.Sorted(maps.Keys(standbys)) {
		if err := reload(standbys[name]); err != nil {
			return fmt.Errorf("standby %s: %w", name, err)
		}
	}
	return nil
}

// restartForParameters restarts the PostgreSQL pod by setting the
// parameters-restart pod template annotation to hash (the configuration to
// load). Like restartForTLS it restarts at most once per configuration: when
// the annotation already has this value nothing is done.
func (r *ClusterReconciler) restartForParameters(ctx context.Context, cluster *postgresv1alpha1.Cluster, hash string) error {
	sts := &appsv1.StatefulSet{}
	if err := r.Get(ctx, types.NamespacedName{Name: cluster.Name, Namespace: cluster.Namespace}, sts); err != nil {
		return err
	}
	if sts.Spec.Template.Annotations[AnnotationParametersRestart] == hash {
		return nil
	}
	base := sts.DeepCopy()
	if sts.Spec.Template.Annotations == nil {
		sts.Spec.Template.Annotations = map[string]string{}
	}
	sts.Spec.Template.Annotations[AnnotationParametersRestart] = hash
	if err := r.Patch(ctx, sts, client.MergeFrom(base)); err != nil {
		return err
	}
	logf.FromContext(ctx).Info("Restarting the PostgreSQL pod to apply parameters that need a restart")
	if r.Recorder != nil {
		r.Recorder.Eventf(cluster, sts, corev1.EventTypeNormal, ReasonPendingRestart, "RestartForParameters",
			"Restarting the PostgreSQL pod: spec.parameters changed parameters that only take effect on a restart")
	}
	return nil
}
