/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"fmt"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"

	postgresv1alpha1 "github.com/ruckc/pgop/api/v1alpha1"
	"github.com/ruckc/pgop/internal/postgres"
)

const (
	pg18Data     = "/var/lib/postgresql/18/docker"
	pg18AutoConf = pg18Data + "/" + autoConfFileName
	testWorkMem  = "work_mem"
	testSPL      = "shared_preload_libraries"
	testPGSS     = "pg_stat_statements"
	test8MB      = "8MB"
	testMaxConn  = "max_connections"
	testCtxUser  = "user"
	testSSLOn    = "ssl=on"
)

var _ = Describe("Generated configuration file", func() {
	It("renders sorted, quoted parameters after the data directory's postgresql.conf", func() {
		conf, hash := renderPostgresConf(map[string]string{
			testWorkMem:       test8MB,
			testMaxConn:       "200",
			"search_path":     `"$user", public`,
			"log_line_prefix": `it's %m \ %p`,
		}, pg18Data)
		Expect(conf).To(Equal(`# Generated by pgop from Cluster spec.parameters. Changes are overwritten.
include_if_exists '/var/lib/postgresql/18/docker/postgresql.conf'
log_line_prefix = 'it''s %m \\ %p'
max_connections = '200'
search_path = '"$user", public'
work_mem = '8MB'
`))
		Expect(hash).To(HaveLen(64))

		By("being deterministic")
		for range 10 {
			_, again := renderPostgresConf(map[string]string{
				testMaxConn: "200", testWorkMem: test8MB, "search_path": `"$user", public`,
				"log_line_prefix": `it's %m \ %p`,
			}, pg18Data)
			Expect(again).To(Equal(hash))
		}
	})

	It("includes the PG <=17 data directory and changes the hash with it", func() {
		conf16, h16 := renderPostgresConf(map[string]string{testWorkMem: test8MB}, layoutForMajor(16).PGDATA)
		Expect(conf16).To(ContainSubstring("include_if_exists '/var/lib/postgresql/data/postgresql.conf'\n"))
		_, h18 := renderPostgresConf(map[string]string{testWorkMem: test8MB}, layoutForMajor(18).PGDATA)
		Expect(h16).NotTo(Equal(h18))
	})

	It("escapes line breaks so a value can never end its line", func() {
		Expect(quoteConfValue("a\nb\rc")).To(Equal(`'a\nb\rc'`))
		Expect(parametersWithLineBreaks(map[string]string{"a": "x\ny", "b": "ok", "c": "\r"})).
			To(Equal([]string{"a", "c"}))
	})

	It("renders only the include for an empty map", func() {
		conf, _ := renderPostgresConf(nil, pg18Data)
		Expect(strings.Count(conf, "\n")).To(Equal(2))
	})

	It("finds names that differ only in case", func() {
		Expect(duplicateParameters(map[string]string{"Work_Mem": "1", testWorkMem: "2", "a": "b"})).
			To(Equal([]string{testWorkMem}))
		Expect(duplicateParameters(map[string]string{testWorkMem: "2"})).To(BeEmpty())
	})

	DescribeTable("server args",
		func(tls *postgresv1alpha1.ClusterTLSSpec, params map[string]string, want []string) {
			c := &postgresv1alpha1.Cluster{Spec: postgresv1alpha1.ClusterSpec{TLS: tls, Parameters: params}}
			Expect(postgresServerArgs(c)).To(Equal(want))
		},
		Entry("neither", nil, nil, nil),
		Entry("empty parameters", nil, map[string]string{}, nil),
		Entry("parameters only", nil, map[string]string{testWorkMem: test8MB},
			[]string{postgresBinary, "-c", "config_file=/etc/pgop/config/postgresql.conf"}),
		Entry("TLS only, unchanged", &postgresv1alpha1.ClusterTLSSpec{RequireTLS: new(false)}, nil,
			[]string{postgresBinary, "-c", testSSLOn, "-c", "ssl_cert_file=/etc/pgop/tls/tls.crt",
				"-c", "ssl_key_file=/etc/pgop/tls/tls.key", "-c", "ssl_min_protocol_version=TLSv1.2"}),
		Entry("both", &postgresv1alpha1.ClusterTLSSpec{}, map[string]string{testWorkMem: test8MB},
			[]string{postgresBinary, "-c", "config_file=/etc/pgop/config/postgresql.conf",
				"-c", testSSLOn, "-c", "ssl_cert_file=/etc/pgop/tls/tls.crt",
				"-c", "ssl_key_file=/etc/pgop/tls/tls.key", "-c", "ssl_min_protocol_version=TLSv1.2",
				"-c", "hba_file=/etc/pgop/hba/pg_hba.conf"}),
	)

	Context("assessParameters", func() {
		ourFile := func(name, setting, errMsg string) postgres.FileSetting {
			return postgres.FileSetting{SourceFile: configFilePath, Name: name, Setting: setting, Error: errMsg}
		}
		params := map[string]string{testWorkMem: test8MB, testSPL: testPGSS}

		It("waits for the server to use the generated file and for the file to sync", func() {
			a := assessParameters(params, pg18Data+"/postgresql.conf", nil, nil, pg18AutoConf)
			Expect(a.UsesGeneratedFile).To(BeFalse())

			files := []postgres.FileSetting{
				{SourceFile: pg18Data + "/postgresql.conf", Name: "listen_addresses", Setting: "*"},
				ourFile(testWorkMem, "4MB", ""),
				ourFile(testSPL, testPGSS, ""),
			}
			a = assessParameters(params, configFilePath, files, nil, pg18AutoConf)
			Expect(a.UsesGeneratedFile).To(BeTrue())
			Expect(a.Synced).To(BeFalse())

			files[1].Setting = test8MB
			Expect(assessParameters(params, configFilePath, files, nil, pg18AutoConf).Synced).To(BeTrue())

			By("noticing a parameter that is still in the file but no longer desired")
			stale := []postgres.FileSetting{files[1], files[2], ourFile(testMaxConn, "200", "")}
			Expect(assessParameters(params, configFilePath, stale, nil, pg18AutoConf).Synced).To(BeFalse())
		})

		It("compares names case-insensitively", func() {
			a := assessParameters(map[string]string{"Work_Mem": test8MB}, configFilePath,
				[]postgres.FileSetting{ourFile("Work_Mem", test8MB, "")},
				[]postgres.Setting{{Name: testWorkMem, Context: testCtxUser, SourceFile: configFilePath}}, pg18AutoConf)
			Expect(a.Synced).To(BeTrue())
			Expect(a.Invalid).To(BeEmpty())
		})

		It("rejects unknown names and invalid values before reloading", func() {
			a := assessParameters(map[string]string{"wrk_mem": "1", testWorkMem: "lots"}, configFilePath,
				[]postgres.FileSetting{
					ourFile("wrk_mem", "1", "unrecognized configuration parameter"),
					ourFile(testWorkMem, "lots", "setting could not be applied"),
				},
				[]postgres.Setting{{Name: testWorkMem, Context: testCtxUser}}, pg18AutoConf)
			Expect(a.Synced).To(BeTrue())
			Expect(a.Invalid).To(ConsistOf(
				"wrk_mem = '1': unrecognized configuration parameter",
				"work_mem = 'lots': setting could not be applied"))
		})

		It("tells a pending restart from an invalid restart-only value after a reload", func() {
			files := []postgres.FileSetting{ourFile(testSPL, testPGSS, "setting could not be applied")}
			p := map[string]string{testSPL: testPGSS}

			a := assessParameters(p, configFilePath, files,
				[]postgres.Setting{{Name: testSPL, Context: pgContextPostmaster, PendingRestart: true, SourceFile: pg18Data + "/postgresql.conf"}},
				pg18AutoConf)
			Expect(a.Invalid).To(BeEmpty())
			Expect(a.InvalidAfterReload).To(BeEmpty())
			Expect(a.Pending).To(Equal([]string{testSPL}))
			Expect(a.RestartNeeded).To(BeTrue())

			a = assessParameters(p, configFilePath, files,
				[]postgres.Setting{{Name: testSPL, Context: pgContextPostmaster}}, pg18AutoConf)
			Expect(a.Invalid).To(BeEmpty())
			Expect(a.InvalidAfterReload).To(HaveLen(1))
			Expect(a.RestartNeeded).To(BeFalse())
		})

		It("restarts for a removed restart-only parameter but not for unrelated pending ones", func() {
			a := assessParameters(map[string]string{testWorkMem: test8MB}, configFilePath,
				[]postgres.FileSetting{ourFile(testWorkMem, test8MB, "")},
				[]postgres.Setting{{Name: testSPL, Context: pgContextPostmaster, PendingRestart: true, SourceFile: configFilePath}},
				pg18AutoConf)
			Expect(a.RestartNeeded).To(BeTrue())

			a = assessParameters(map[string]string{testWorkMem: test8MB}, configFilePath,
				[]postgres.FileSetting{ourFile(testWorkMem, test8MB, "")},
				[]postgres.Setting{{Name: testMaxConn, Context: pgContextPostmaster, PendingRestart: true, SourceFile: pg18AutoConf}},
				pg18AutoConf)
			Expect(a.RestartNeeded).To(BeFalse())
			Expect(a.Pending).To(Equal([]string{testMaxConn}))
		})

		It("reports parameters overridden by ALTER SYSTEM", func() {
			a := assessParameters(params, configFilePath, nil,
				[]postgres.Setting{
					{Name: testWorkMem, Context: testCtxUser, Source: "configuration file", SourceFile: pg18AutoConf},
					{Name: testSPL, Context: pgContextPostmaster, SourceFile: configFilePath},
				}, pg18AutoConf)
			Expect(a.Overridden).To(Equal([]string{testWorkMem}))
		})
	})
})

// fakeParameterServer stands in for PostgreSQL in envtest.
type fakeParameterServer struct {
	configFile string
	files      []postgres.FileSetting
	settings   []postgres.Setting
	reloads    int
	connects   []postgres.ConnectionConfig
	err        error
}

func (f *fakeParameterServer) ConfigFile(context.Context) (string, error) { return f.configFile, f.err }
func (f *fakeParameterServer) FileSettings(context.Context) ([]postgres.FileSetting, error) {
	return f.files, f.err
}
func (f *fakeParameterServer) Settings(context.Context) ([]postgres.Setting, error) {
	return f.settings, f.err
}
func (f *fakeParameterServer) ReloadConfig(context.Context) error {
	f.reloads++
	return f.err
}
func (f *fakeParameterServer) Close() error { return nil }

// serve makes the fake report params as loaded from the generated file.
func (f *fakeParameterServer) serve(params map[string]string) {
	f.configFile = configFilePath
	f.files = nil
	f.settings = nil
	for k, v := range params {
		f.files = append(f.files, postgres.FileSetting{SourceFile: configFilePath, Name: k, Setting: v})
		f.settings = append(f.settings, postgres.Setting{Name: k, Context: testCtxUser, Source: "configuration file", SourceFile: configFilePath})
	}
}

var _ = Describe("Cluster parameters", func() {
	var (
		ctx  context.Context
		name string
		fake *fakeParameterServer
	)

	BeforeEach(func() {
		ctx = context.Background()
		name = fmt.Sprintf("params-%d", time.Now().UnixNano())
		fake = &fakeParameterServer{}
	})

	key := func() types.NamespacedName { return types.NamespacedName{Name: name, Namespace: testTLSNamespace} }

	newCluster := func(params map[string]string) *postgresv1alpha1.Cluster {
		return &postgresv1alpha1.Cluster{
			ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: testTLSNamespace},
			Spec:       postgresv1alpha1.ClusterSpec{Image: DefaultPostgresImage, Parameters: params},
		}
	}
	createCluster := func(params map[string]string) {
		c := newCluster(params)
		Expect(k8sClient.Create(ctx, c)).To(Succeed())
		DeferCleanup(func() {
			c.SetFinalizers(nil)
			_ = k8sClient.Update(ctx, c)
			_ = k8sClient.Delete(ctx, c)
		})
	}
	getCluster := func() *postgresv1alpha1.Cluster {
		c := &postgresv1alpha1.Cluster{}
		Expect(k8sClient.Get(ctx, key(), c)).To(Succeed())
		return c
	}
	setParams := func(params map[string]string) {
		c := getCluster()
		c.Spec.Parameters = params
		Expect(k8sClient.Update(ctx, c)).To(Succeed())
	}
	getSTS := func() *appsv1.StatefulSet {
		sts := &appsv1.StatefulSet{}
		Expect(k8sClient.Get(ctx, key(), sts)).To(Succeed())
		return sts
	}
	markSTSReady := func() {
		sts := getSTS()
		sts.Status.Replicas = 1
		sts.Status.ReadyReplicas = 1
		Expect(k8sClient.Status().Update(ctx, sts)).To(Succeed())
		ensureSTSPod(sts, 0, true)
	}
	getConfigMap := func() (*corev1.ConfigMap, error) {
		cm := &corev1.ConfigMap{}
		err := k8sClient.Get(ctx, types.NamespacedName{Name: name + "-config", Namespace: testTLSNamespace}, cm)
		return cm, err
	}
	condition := func() *metav1.Condition {
		return meta.FindStatusCondition(getCluster().Status.Conditions, ConditionTypeParametersApplied)
	}
	newReconciler := func() *ClusterReconciler {
		return &ClusterReconciler{
			Client: k8sClient,
			Scheme: k8sClient.Scheme(),
			ConnectParameterServer: func(_ context.Context, cfg postgres.ConnectionConfig) (ParameterServer, error) {
				fake.connects = append(fake.connects, cfg)
				return fake, nil
			},
		}
	}
	reconcileOnce := func(r *ClusterReconciler) time.Duration {
		res, err := r.Reconcile(ctx, reconcileRequest(getCluster()))
		Expect(err).NotTo(HaveOccurred())
		return res.RequeueAfter
	}

	Context("validation", func() {
		It("accepts ordinary and extension parameters", func() {
			c := newCluster(map[string]string{testWorkMem: test8MB, "pg_stat_statements.max": "10000", "Search_Path": "a, b"})
			Expect(k8sClient.Create(ctx, c)).To(Succeed())
			Expect(k8sClient.Delete(ctx, c)).To(Succeed())
		})

		for _, reserved := range append(append([]string{}, postgresv1alpha1.ReservedParameters...), "Port", "SSL_Cert_File") {
			It("rejects the operator-managed parameter "+reserved, func() {
				err := k8sClient.Create(ctx, newCluster(map[string]string{reserved: "x"}))
				Expect(apierrors.IsInvalid(err)).To(BeTrue(), "got %v", err)
				Expect(err.Error()).To(ContainSubstring("operator-managed"))
			})
		}

		DescribeTable("rejects malformed entries",
			func(params map[string]string, msg string) {
				err := k8sClient.Create(ctx, newCluster(params))
				Expect(apierrors.IsInvalid(err)).To(BeTrue(), "got %v", err)
				Expect(err.Error()).To(ContainSubstring(msg))
			},
			Entry("dash in name", map[string]string{"work-mem": "1"}, "parameter names must match"),
			Entry("leading digit", map[string]string{"1x": "1"}, "parameter names must match"),
			Entry("space in name", map[string]string{"work mem": "1"}, "parameter names must match"),
			Entry("newline in name", map[string]string{"work_mem\ninclude": "1"}, "parameter names must match"),
		)
	})

	It("leaves a Cluster without parameters exactly as before", func() {
		createCluster(nil)
		r := newReconciler()
		reconcileOnce(r)
		markSTSReady()
		reconcileOnce(r)

		sts := getSTS()
		Expect(sts.Spec.Template.Spec.Volumes).To(BeEmpty())
		Expect(sts.Spec.Template.Spec.Containers[0].Args).To(BeEmpty())
		_, err := getConfigMap()
		Expect(apierrors.IsNotFound(err)).To(BeTrue())
		Expect(condition()).To(BeNil())
		Expect(fake.connects).To(BeEmpty(), "never connects for a Cluster without parameters")
	})

	It("mounts an owned ConfigMap and only updates it when a parameter changes", func() {
		createCluster(map[string]string{testWorkMem: test8MB})
		r := newReconciler()
		reconcileOnce(r)

		cm, err := getConfigMap()
		Expect(err).NotTo(HaveOccurred())
		Expect(metav1.IsControlledBy(cm, getCluster())).To(BeTrue())
		Expect(cm.Data[configFileName]).To(ContainSubstring("work_mem = '8MB'\n"))
		Expect(cm.Data[configFileName]).To(ContainSubstring("include_if_exists '" + pg18Data + "/postgresql.conf'"))

		sts := getSTS()
		c := sts.Spec.Template.Spec.Containers[0]
		Expect(c.Args).To(Equal([]string{postgresBinary, "-c", "config_file=" + configFilePath}))
		Expect(c.VolumeMounts).To(ContainElement(corev1.VolumeMount{Name: configVolumeName, MountPath: configMountPath, ReadOnly: true}))
		Expect(sts.Spec.Template.Spec.Volumes).To(HaveLen(1))
		Expect(sts.Spec.Template.Spec.Volumes[0].ConfigMap.Name).To(Equal(name + "-config"))

		cond := condition()
		Expect(cond.Status).To(Equal(metav1.ConditionFalse))
		Expect(cond.Reason).To(Equal(ReasonWaitingForServer))

		By("changing a parameter")
		rv := getSTS().ResourceVersion
		setParams(map[string]string{testWorkMem: "16MB", testSPL: testPGSS})
		reconcileOnce(r)
		cm, err = getConfigMap()
		Expect(err).NotTo(HaveOccurred())
		Expect(cm.Data[configFileName]).To(ContainSubstring("work_mem = '16MB'\n"))
		Expect(cm.Data[configFileName]).To(ContainSubstring("shared_preload_libraries = 'pg_stat_statements'\n"))
		Expect(getSTS().ResourceVersion).To(Equal(rv), "a parameter change must not roll the pod")
	})

	It("adds the config file to an existing StatefulSet and removes it again", func() {
		createCluster(nil)
		r := newReconciler()
		reconcileOnce(r)
		Expect(getSTS().Spec.Template.Spec.Containers[0].Args).To(BeEmpty())

		By("adding the first parameter")
		setParams(map[string]string{testWorkMem: test8MB})
		reconcileOnce(r)
		Expect(getSTS().Spec.Template.Spec.Containers[0].Args).To(ContainElement("config_file=" + configFilePath))
		_, err := getConfigMap()
		Expect(err).NotTo(HaveOccurred())

		By("removing the last parameter")
		setParams(nil)
		reconcileOnce(r)
		sts := getSTS()
		Expect(sts.Spec.Template.Spec.Containers[0].Args).To(BeEmpty())
		Expect(sts.Spec.Template.Spec.Volumes).To(BeEmpty())
		Expect(sts.Spec.Template.Spec.Containers[0].VolumeMounts).To(HaveLen(1))
		_, err = getConfigMap()
		Expect(apierrors.IsNotFound(err)).To(BeTrue())
		Expect(condition()).To(BeNil())
		Expect(getCluster().Status.ParametersHash).To(BeEmpty())
	})

	It("reloads changed parameters and restarts the pod once for restart-only ones", func() {
		params := map[string]string{testWorkMem: test8MB}
		createCluster(params)
		r := newReconciler()
		reconcileOnce(r)
		markSTSReady()

		By("waiting until the server uses the generated file")
		fake.configFile = pg18Data + "/postgresql.conf"
		Expect(reconcileOnce(r)).To(Equal(parametersPollInterval))
		Expect(condition().Reason).To(Equal(ReasonWaitingForSync))
		Expect(fake.reloads).To(BeZero())
		Expect(fake.connects[0].Host).To(Equal(name + "." + testTLSNamespace + ".svc.cluster.local"))
		Expect(fake.connects[0].SSLMode).To(Equal(postgres.SSLModeDisable))

		By("waiting until the kubelet synced the file")
		fake.serve(map[string]string{testWorkMem: "4MB"})
		reconcileOnce(r)
		Expect(condition().Reason).To(Equal(ReasonWaitingForSync))
		Expect(fake.reloads).To(BeZero())

		By("reloading once the file is synced")
		fake.serve(params)
		Expect(reconcileOnce(r)).To(Equal(parametersReloadCheckDelay))
		Expect(fake.reloads).To(Equal(1))
		Expect(condition().Reason).To(Equal(ReasonParametersReloading))
		hash := getCluster().Status.ParametersHash
		Expect(hash).NotTo(BeEmpty())

		By("reporting the parameters applied without another reload")
		reconcileOnce(r)
		Expect(fake.reloads).To(Equal(1))
		cond := condition()
		Expect(cond.Status).To(Equal(metav1.ConditionTrue))
		Expect(cond.Reason).To(Equal(ReasonParametersApplied))
		Expect(getSTS().Spec.Template.Annotations).NotTo(HaveKey(AnnotationParametersRestart))

		By("adding a parameter that needs a restart")
		params = map[string]string{testWorkMem: test8MB, testSPL: testPGSS}
		setParams(params)
		fake.serve(params)
		for i := range fake.files {
			if fake.files[i].Name == testSPL {
				fake.files[i].Error = "setting could not be applied"
			}
		}
		for i := range fake.settings {
			if fake.settings[i].Name == testSPL {
				fake.settings[i] = postgres.Setting{Name: testSPL, Context: pgContextPostmaster,
					SourceFile: pg18Data + "/postgresql.conf", PendingRestart: true}
			}
		}
		reconcileOnce(r)
		Expect(fake.reloads).To(Equal(2))
		Expect(getCluster().Status.ParametersHash).NotTo(Equal(hash))
		reconcileOnce(r)
		c := getCluster()
		Expect(c.Status.PendingRestart).To(Equal([]string{testSPL}))
		cond = meta.FindStatusCondition(c.Status.Conditions, ConditionTypeParametersApplied)
		Expect(cond.Reason).To(Equal(ReasonPendingRestart))
		sts := getSTS()
		Expect(sts.Spec.Template.Annotations[AnnotationParametersRestart]).To(Equal(c.Status.ParametersHash))

		By("not restarting again for the same configuration")
		reconcileOnce(r)
		Expect(getSTS().ResourceVersion).To(Equal(sts.ResourceVersion))

		By("reporting the parameters applied once the restarted server has them")
		fake.serve(params)
		reconcileOnce(r)
		c = getCluster()
		Expect(c.Status.PendingRestart).To(BeEmpty())
		Expect(meta.IsStatusConditionTrue(c.Status.Conditions, ConditionTypeParametersApplied)).To(BeTrue())
		Expect(fake.reloads).To(Equal(2))
	})

	It("reports invalid parameters without reloading or restarting", func() {
		params := map[string]string{testWorkMem: "lots"}
		createCluster(params)
		r := newReconciler()
		reconcileOnce(r)
		markSTSReady()

		fake.serve(params)
		fake.files[0].Error = "setting could not be applied"
		Expect(reconcileOnce(r)).To(Equal(parametersInvalidRecheck))
		cond := condition()
		Expect(cond.Status).To(Equal(metav1.ConditionFalse))
		Expect(cond.Reason).To(Equal(ReasonInvalidParameter))
		Expect(cond.Message).To(ContainSubstring("work_mem = 'lots'"))
		Expect(fake.reloads).To(BeZero())
		Expect(getSTS().Spec.Template.Annotations).NotTo(HaveKey(AnnotationParametersRestart))
	})

	It("reports values with line breaks without connecting", func() {
		createCluster(map[string]string{testWorkMem: "1MB\ninclude '/etc/passwd'"})
		r := newReconciler()
		reconcileOnce(r)
		markSTSReady()
		reconcileOnce(r)
		cond := condition()
		Expect(cond.Reason).To(Equal(ReasonInvalidParameter))
		Expect(cond.Message).To(ContainSubstring("line breaks"))
		Expect(fake.connects).To(BeEmpty())
		cm, err := getConfigMap()
		Expect(err).NotTo(HaveOccurred())
		Expect(cm.Data[configFileName]).To(ContainSubstring(`work_mem = '1MB\ninclude ''/etc/passwd'''` + "\n"))
	})

	It("reports names that differ only in case", func() {
		createCluster(map[string]string{testWorkMem: "1MB", "WORK_MEM": "2MB"})
		r := newReconciler()
		reconcileOnce(r)
		markSTSReady()
		reconcileOnce(r)
		Expect(condition().Reason).To(Equal(ReasonInvalidParameter))
		Expect(fake.connects).To(BeEmpty())
	})

	It("reports parameters overridden by ALTER SYSTEM", func() {
		params := map[string]string{testWorkMem: test8MB}
		createCluster(params)
		r := newReconciler()
		reconcileOnce(r)
		markSTSReady()
		fake.serve(params)
		reconcileOnce(r) // reload
		fake.settings[0].SourceFile = pg18AutoConf
		Expect(reconcileOnce(r)).To(Equal(parametersRecheckInterval))
		cond := condition()
		Expect(cond.Status).To(Equal(metav1.ConditionFalse))
		Expect(cond.Reason).To(Equal(ReasonOverriddenByAlterSystem))
		Expect(cond.Message).To(ContainSubstring(testWorkMem))
	})

	It("keeps the Cluster available when the server cannot be queried", func() {
		createCluster(map[string]string{testWorkMem: test8MB})
		r := newReconciler()
		reconcileOnce(r)
		markSTSReady()
		fake.err = fmt.Errorf("connection refused")
		Expect(reconcileOnce(r)).To(Equal(parametersRetryInterval))
		c := getCluster()
		Expect(c.Status.Ready).To(BeTrue())
		cond := meta.FindStatusCondition(c.Status.Conditions, ConditionTypeParametersApplied)
		Expect(cond.Reason).To(Equal(ReasonWaitingForServer))
		Expect(cond.Message).To(ContainSubstring("connection refused"))
	})

	It("combines the config file with TLS", func() {
		ca := newTestCA()
		tlsSecret := &corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: name + "-tls", Namespace: testTLSNamespace},
			Type:       corev1.SecretTypeTLS,
			Data:       ca.issueFor(name + "." + testTLSNamespace + ".svc.cluster.local"),
		}
		Expect(k8sClient.Create(ctx, tlsSecret)).To(Succeed())
		DeferCleanup(func() { _ = k8sClient.Delete(ctx, tlsSecret) })
		c := newCluster(map[string]string{testWorkMem: test8MB})
		c.Spec.TLS = &postgresv1alpha1.ClusterTLSSpec{SecretName: name + "-tls"}
		Expect(k8sClient.Create(ctx, c)).To(Succeed())
		DeferCleanup(func() {
			c.SetFinalizers(nil)
			_ = k8sClient.Update(ctx, c)
			_ = k8sClient.Delete(ctx, c)
		})
		reconcileOnce(newReconciler())

		sts := getSTS()
		Expect(sts.Spec.Template.Spec.Containers[0].Args).To(ContainElements(
			"config_file="+configFilePath, testSSLOn, "hba_file=/etc/pgop/hba/pg_hba.conf"))
		Expect(sts.Spec.Template.Spec.Volumes).To(HaveLen(3))
		Expect(sts.Spec.Template.Spec.Containers[0].VolumeMounts).To(HaveLen(4))
	})
})
