---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgop.ruck.io
  resources:
  - backupruns
  - backups
  - clusters
  - databases
  - restores
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgop.ruck.io
  resources:
  - backupruns/finalizers
  - backups/finalizers
  - clusters/finalizers
  - databases/finalizers
  - restores/finalizers
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - pgop.ruck.io
  resources:
  - backupruns/status
  - backups/status
  - clusters/status
  - databases/status
  - restores/status
  - roles/status
  verbs:
  - get
  - patch
  - update
