apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pgop.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgop.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pgop.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "pgop.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
